In [55]:
import pandas as pd
import numpy as np
import datetime as dt
from sklearn import linear_model
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

from sklearn.cross_validation import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
%matplotlib inline

In [56]:
full_data = pd.read_csv('../data/adri_data/entrenamiento_postulaciones_vistas3.csv', encoding='utf-8')
full_data.shape

(9560543, 15)

In [57]:
full_data.head()

idaviso            timestamp  valor_educacion  sexo  edad  idtitulo  \
0  1111556097  2018-03-13 16:23:14               17     1  44.0         0   
1  1112370711  2018-03-08 14:28:36               17     1  44.0      6996   
2  1112326655  2018-02-09 14:35:24               17     1  44.0     11827   
3  1112350182  2018-02-20 15:16:56               17     1  44.0      2141   
4  1112383837  2018-03-07 14:18:18               17     1  44.0      6942   

   idzona  idciudad  idmapacalle  idtipo_de_trabajo  idnivel_laboral  \
0       0         0            0                  0                0   
1       0         0            0                  0                0   
2       0         0            0                  0                0   
3       0         0            0                  0                0   
4       0         0            0                  0                0   

   idnombre_area  iddenominacion_empresa  se_postulo  idpostulante  
0              0                       0           1        365446  
1             45                      14           1        365446  
2              4                      33           1        365446  
3             31                      38           1        365446  
4             75                      46           1        365446

In [58]:
df = full_data[['idaviso', 'idpostulante', 'valor_educacion', 'sexo', 'idtitulo', 
                'idzona', 'idciudad', 'idmapacalle', 'idtipo_de_trabajo', 'idnivel_laboral'
'idnombre_area'
'iddenominacion_empresa'
                'se_postulo']]

In [59]:
# X will have the numeric data, Y will have the target class
X = np.array(df.ix[:, 0:5])
y = np.array(df['se_postulo']) 

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  


In [60]:
# Split into train and test, use only 10% as test (15 flowers)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10, random_state=7506)
X_test

array([[1112418765,      25634,         10,          1,       1432],
       [1112342538,     124354,         11,          1,         12],
       [1112277642,     226590,         12,          2,        170],
       ...,
       [1112378650,     152443,         10,          1,       8804],
       [1112190137,     104065,          6,          2,      10470],
       [1112312221,     206854,          6,          2,       8553]],
      dtype=int64)

In [61]:
y_test

array([0, 1, 1, ..., 1, 1, 1], dtype=int64)

In [75]:
# Create KNN classifier
knn = KNeighborsClassifier(n_neighbors=3)

In [76]:
# FIT (this does nothing in normal KNN)
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [77]:
# predict the response
pred = knn.predict(X_test)
pred.shape

(956055,)

In [78]:
# evaluate accuracy
print (accuracy_score(y_test, pred))

0.7462583219584648


In [79]:
pred_df = pd.DataFrame(pred)
pred_df.head()

0
0  0
1  1
2  1
3  0
4  1

# Predigo con todos los datos

In [117]:
X_full_data = np.array(df.ix[:, 0:5])
X_full_data

array([[1111556097,     365446,         17,          1,          0],
       [1112370711,     365446,         17,          1,       6996],
       [1112326655,     365446,         17,          1,      11827],
       ...,
       [1111601884,     323892,         12,          1,      20596],
       [1111319984,     399727,         10,          1,      20463],
       [1112084920,     120330,          6,         -1,       1344]],
      dtype=int64)

In [118]:
pred_full_data = knn.predict(X_full_data)

In [119]:
pred_full_data

array([1, 0, 1, ..., 0, 0, 1], dtype=int64)

In [123]:
df['sepostulo'] = pred_full_data

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [124]:
df

idaviso  idpostulante  valor_educacion  sexo  idtitulo  \
0        1111556097        365446               17     1         0   
1        1112370711        365446               17     1      6996   
2        1112326655        365446               17     1     11827   
3        1112350182        365446               17     1      2141   
4        1112383837        365446               17     1      6942   
5        1112394991        365446               17     1     12402   
6        1112387712        365446               17     1     10734   
7        1112286220        365446               17     1      2521   
8        1112399795        365446               17     1     13335   
9        1112296014        365446               17     1      4946   
10       1112289548        365446               17     1      3373   
11       1112296354        365446               17     1      5057   
12       1111967504        365446               17     1      4746   
13       1112407372        365446               17     1     15244   
14       1111984070        365446               17     1      2253   
15       1112365178        365446               17     1      5841   
16       1112252821        365446               17     1      9934   
17       1112424614        365446               17     1      4421   
18       1112336070        365446               17     1      6277   
19       1112432317        365446               17     1       171   
20       1112458730        365446               17     1     12040   
21       1112349399        365446               17     1      1948   
22       1112463121        365446               17     1     12869   
23       1112382267        365446               17     1      9238   
24       1111556097        209736                6     2         0   
25       1112191071        209736                6     2     10713   
26       1111891857        209736                6     2      2264   
27       1112422110        209736                6     2      3784   
28       1112396891        209736                6     2     12706   
29       1112353872        209736                6     2      3084   
...             ...           ...              ...   ...       ...   
9560513  1112054114        157394               10    -1      9459   
9560514  1112194374        385974                4     1     20678   
9560515  1112296586        118649               10     1      1784   
9560516  1111947938        348860                6     2     20739   
9560517  1111682210        256357               12     1     10638   
9560518  1111682210         69137               10     1     10638   
9560519  1111923911        153813               12     1     20630   
9560520  1111549543        379758               11     1      4280   
9560521  1111840748        342668               10     2     20392   
9560522  1111177561         31690               10     1      1742   
9560523  1111858589         23662               12     2     20622   
9560524  1111322472        104312                6     2     20464   
9560525  1111469472        390629                5     1     20586   
9560526  1111471769        374031               10     2     20601   
9560527  1111460314         22534               12     2     20473   
9560528  1112087976         51478                8     2      5342   
9560529  1112097280        113023               10     1     20431   
9560530  1000872556        325512                6     2     20230   
9560531  1112055574        169268                6     1     20651   
9560532  1112100433        132814               11     1      1334   
9560533  1112049386        352522                6     2     20540   
9560534  1112226525         52119                8     1      3980   
9560535  1111872834        103879                6     2     20727   
9560536  1111943777        359331                6     1      3162   
9560537  1111998205         59278               12     1     20643   
9560538  1112254462   

# Finalmente, preparo el archivo para subir-

In [145]:
top100 = pd.read_csv("../test_final_100k.csv", encoding='utf-8')
top100.head()

id  idaviso idpostulante
0   0   739260       6M9ZQR
1   1   739260       6v1xdL
2   2   739260       ezRKm9
3   3   758580       1Q35ej
4   4   758580       EAN4J6

In [146]:
top100.shape

(100000, 3)

In [147]:
id_postulantes = pd.read_csv('../data/adri_data/entrenamiento_id_postulantes.csv', encoding='utf-8')
id_postulantes.drop('Unnamed: 0', axis=1, inplace=True)
id_postulantes.shape
id_postulantes.head()

idpostulante  idpostulante2
0      pzeVW63         365446
1      PmVbBWY         209736
2      zvPMxvJ         409297
3       YYwJKq         250105
4      3NkMAVq          37024

In [148]:
top100_full = pd.merge(top100, id_postulantes, how='left', on='idpostulante')
top100_full.shape

(100000, 4)

In [149]:
top100_full.drop('idpostulante', inplace=True, axis=1)
top100_full.rename({'idpostulante2':'idpostulante'}, inplace=True, axis=1)
top100_full.head()

id  idaviso  idpostulante
0   0   739260       63651.0
1   1   739260       76877.0
2   2   739260      323397.0
3   3   758580           NaN
4   4   758580      127342.0

In [150]:
top100_full = pd.merge(top100_full, df, how='left', on=['idaviso','idpostulante'])
top100_full.shape

(100000, 8)

In [151]:
top100_full = top100_full[['id', 'sepostulo']]
top100_full.head()

id  sepostulo
0   0        NaN
1   1        NaN
2   2        NaN
3   3        NaN
4   4        NaN

In [152]:
top100_full.fillna(0, inplace=True)

In [155]:
top100_full['sepostulo'] = top100_full['sepostulo'].astype('int')
top100_full.head()

id  sepostulo
0   0          0
1   1          0
2   2          0
3   3          0
4   4          0

In [157]:
top100_full[top100_full['sepostulo'] == 1].shape

(22668, 2)

In [158]:
# top100_full.rename({'se_postulo' : 'sepostulo'}, inplace=True, axis=1)
top100_full.to_csv('../data/adri_data/top100k.csv', encoding='utf-8', index=False)