In [7]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
%matplotlib inline
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [28]:
df = pd.read_csv('../data/adri_data/entrenamiento_postulaciones_vistas5.csv', encoding='utf-8')
df.head()

idaviso     timestamp  valor_educacion  sexo  edad  idtitulo  idzona  \
0  1112363488  8.617918e+06               12     1    34     15677       0   
1  1112299213  1.101489e+07                9     2    24      9371       0   
2  1112425871  6.232296e+06               16     2    25     10775       0   
3  1112208765  1.005179e+07               11     2    32     15848       0   
4  1112377689  4.856018e+06               10     1    26     20003       0   

   idciudad  idmapacalle  idtipo_de_trabajo  idnivel_laboral  idnombre_area  \
0         0            0                  0                1            151   
1         0            0                  0                0            182   
2         0            0                  0                1             94   
3         0            0                  0                0              5   
4         0            0                  0                0            182   

   iddenominacion_empresa  se_postulo  idpostulante  
0                      34           1        356027  
1                     127           1        396236  
2                     838           1        125047  
3                     139           1        158791  
4                     391           1         29737

In [29]:
# X will have the numeric data, Y will have the target class
dfix = df.ix[:, 0:13];
X = np.array(dfix)
y = np.array(df['se_postulo']) 

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  


In [30]:
# Split into train and test, use only 10% as test (15 flowers)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10, random_state=7506)
X_test

array([[1.11241580e+09, 5.96798208e+06, 9.00000000e+00, ...,
        1.00000000e+00, 2.90000000e+01, 2.45000000e+02],
       [1.11244858e+09, 4.28078219e+06, 1.00000000e+01, ...,
        5.00000000e+00, 1.36000000e+02, 4.39000000e+02],
       [1.11234994e+09, 8.51570047e+06, 1.00000000e+01, ...,
        0.00000000e+00, 1.57000000e+02, 1.52000000e+02],
       ...,
       [1.11244111e+09, 5.47450086e+06, 9.00000000e+00, ...,
        0.00000000e+00, 1.18000000e+02, 1.05400000e+03],
       [1.11234733e+09, 8.68217886e+06, 6.00000000e+00, ...,
        0.00000000e+00, 1.51000000e+02, 4.78000000e+02],
       [1.11247547e+09, 4.23364338e+06, 1.00000000e+01, ...,
        0.00000000e+00, 2.00000000e+00, 1.28000000e+02]])

In [31]:
clf = DecisionTreeClassifier(max_depth=45)
clf.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=45,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [32]:
# predict the response
pred = clf.predict(X_test)
pred.shape

(1584910,)

In [33]:
print (accuracy_score(y_test, pred))
#max_depth 5 = 0.814749151461
#max_depth 7 = 0.817316995361
#max_depth 9 = 0.830302649952
#max_depth 11 = 0.836146456009
#max_depth 13 = 0.83922786869
#max_depth 15 = 0.842802976816
#max_depth 17 = 0.846111363886
#max_depth 19 = 0.848940699018
#max_depth 21 = 0.852105788893
#max_depth 23 = 0.85494662964
#max_depth 25 = 0.857750861614
#max_depth 27 = 0.860772654293
#max_depth 29 = 0.86390636522
#max_depth 31 = 0.8661049835
#max_depth 35 = 0.869442657588
#max_depth 41 = 0.871770975519
#max_depth 43 = 0.872110914121
#max_depth 44 = 0.872015731313
#max_depth 45 = 0.872120327805
#max_depth 46 = 0.871702987799
#max_depth 47 = 0.872014685348
#max_depth 49 = 0.871613034815
#max_depth 51 = 0.8717626078
#max_depth 61 = 0.8717626078


0.9050659027957424


In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=7506)

In [35]:
clf = DecisionTreeClassifier(max_depth=45)
clf.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=45,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [36]:
# predict the response
pred = clf.predict(X_test)
pred.shape

(3962275,)

In [37]:
print (accuracy_score(y_test, pred))

0.9005806007912122


In [38]:
pred.size

3962275

In [39]:
df.size

237736455

In [40]:
X_full_data = np.array(dfix)
X_full_data

array([[1.11236349e+09, 8.61791765e+06, 1.20000000e+01, ...,
        1.00000000e+00, 1.51000000e+02, 3.40000000e+01],
       [1.11229921e+09, 1.10148866e+07, 9.00000000e+00, ...,
        0.00000000e+00, 1.82000000e+02, 1.27000000e+02],
       [1.11242587e+09, 6.23229565e+06, 1.60000000e+01, ...,
        1.00000000e+00, 9.40000000e+01, 8.38000000e+02],
       ...,
       [1.11179045e+09, 1.18167936e+07, 9.00000000e+00, ...,
        0.00000000e+00, 1.40000000e+01, 6.71000000e+02],
       [1.11239340e+09, 6.17162409e+06, 1.00000000e+01, ...,
        0.00000000e+00, 3.60000000e+01, 7.14000000e+02],
       [1.11247282e+09, 3.90022585e+06, 1.10000000e+01, ...,
        1.00000000e+00, 2.50000000e+01, 1.63600000e+03]])

In [41]:
pred_full_data = clf.predict(X_full_data)

In [42]:
pred_full_data

array([1, 1, 0, ..., 1, 1, 0], dtype=int64)

In [43]:
df['sepostulo'] = pred_full_data

In [44]:
df

idaviso     timestamp  valor_educacion  sexo  edad  idtitulo  \
0         1112363488  8.617918e+06               12     1    34     15677   
1         1112299213  1.101489e+07                9     2    24      9371   
2         1112425871  6.232296e+06               16     2    25     10775   
3         1112208765  1.005179e+07               11     2    32     15848   
4         1112377689  4.856018e+06               10     1    26     20003   
5         1111970596  4.348430e+06               10     1    25     13340   
6         1112286978  5.802213e+06                8     1    42      1311   
7         1112379323  3.462293e+06                6     2    36     13964   
8         1112487359  3.743495e+06                8     2    24      8724   
9         1112429938  5.561723e+06                6     2    36     15892   
10        1112320536  8.877642e+06               11     1    36       858   
11        1112476268  3.837981e+06                9     1    28      1492   
12        1112196813  5.578755e+06                6     1    24      5755   
13        1112132555  9.712118e+06                6     1    19     19459   
14        1112460830  4.695541e+06                5     2    20      4523   
15        1112451106  4.823979e+06                6     2    18     19851   
16        1112216179  8.663005e+06               15     1    36      4725   
17        1112278019  4.720945e+06               12     2    47      7272   
18        1112432376  5.438393e+06                6     1    23     13252   
19        1112196813  5.644823e+06                9     2    24      5755   
20        1112420529  6.263967e+06                7     1    39      8994   
21        1112430991  5.887294e+06               10     2    37      8391   
22        1112403397  4.888828e+06               12     2    27      7431   
23        1112421220  5.907336e+06               12     1    34      3783   
24        1112094756  4.604948e+06                9     1    28     15979   
25        1112398171  7.254046e+06               11     1    25     15409   
26        1112348590  9.044776e+06               12     2    27     19193   
27        1111413600  3.588094e+06                8     1    33     13344   
28        1112267166  1.098261e+07               10     1    21     10518   
29        1112479500  3.757608e+06                8     2    37     20044   
...              ...           ...              ...   ...   ...       ...   
15849067  1112455254  4.781233e+06                8     2    37     13403   
15849068  1112470587  4.070999e+06                5     2    25     14575   
15849069  1112147486  4.804419e+06               12     1    44     16120   
15849070  1112312237  8.502943e+06               10     1    25      4618   
15849071  1112496995  3.392187e+06               11     2    30      5323   
15849072  1112421913  5.546698e+06               10     1    24     15614   
15849073  1112431322  5.994927e+06                8     2    48      8536   
15849074  1112470587  3.298176e+06                4     2    22     14575   
15849075  1112458007  4.755127e+06                9     1    30      5353   
15849076  1112361408  8.650816e+06               11     1    32     12173   
15849077  1112284410  1.021854e+07               12     1    29      8563   
15849078  1112303405  8.500456e+06               10     2    41      6803   
15849079  1112340866  8.025726e+06                9     1    28     19466   
15849080  1112262299  1.171605e+07               17     2    26     10972   
15849081  1112431304  5.489833e+06               10     1    22     15413   
15849082  1111753681  1.139659e+07               11     1    21      6229   
15849083  1112255878  1.197271e+07                6     2    23     14383   
15849084  1112356063  8.565241e+06                5     1    22      4125   
15849085  1112418557  6.536621e+06                6     1    23      9542   
15849086  1112461589  3.584296e+06               12     1    32       919   
15849087 

## File a subir 

In [45]:
top100 = pd.read_csv("../test_final_100k.csv", encoding='utf-8')

In [48]:
id_postulantes = pd.read_csv('../data/adri_data/entrenamiento_id_postulantes.csv', encoding='utf-8')
# id_postulantes.drop('Unnamed: 0', axis=1, inplace=True)
id_postulantes.shape
id_postulantes.head()

idpostulante  idpostulante2
0      pzeVW63         365446
1      PmVbBWY         209736
2      zvPMxvJ         409297
3       YYwJKq         250105
4      3NkMAVq          37024

In [49]:
top100_full = pd.merge(top100, id_postulantes, how='left', on='idpostulante')
top100_full.shape

(100000, 4)

In [50]:
top100_full.drop('idpostulante', inplace=True, axis=1)
top100_full.rename({'idpostulante2':'idpostulante'}, inplace=True, axis=1)
top100_full.head()

id  idaviso  idpostulante
0   0   739260       63651.0
1   1   739260       76877.0
2   2   739260      323397.0
3   3   758580           NaN
4   4   758580      127342.0

In [51]:
top100_full = pd.merge(top100_full, df, how='left', on=['idaviso','idpostulante'])
top100_full.shape

(159370, 17)

In [52]:
top100_full = top100_full[['id', 'se_postulo', 'sepostulo']]
top100_full.head()

id  se_postulo  sepostulo
0   0         NaN        NaN
1   1         NaN        NaN
2   2         NaN        NaN
3   3         NaN        NaN
4   4         NaN        NaN

In [53]:
top100_full.fillna(0, inplace=True)

In [54]:
top100_full['se_postulo'] = top100_full['se_postulo'].astype('int')
top100_full['sepostulo'] = top100_full['sepostulo'].astype('int')
top100_full.head()

id  se_postulo  sepostulo
0   0           0          0
1   1           0          0
2   2           0          0
3   3           0          0
4   4           0          0

In [55]:
top100_full.loc[(top100_full['sepostulo'] == 0) & (top100_full['se_postulo'] == 1), 'sepostulo'] = 1
top100_full[(top100_full['sepostulo'] == 0) & (top100_full['se_postulo'] == 1)]['sepostulo']

Series([], Name: sepostulo, dtype: int32)

In [56]:
top100_full.drop('se_postulo', axis=1, inplace=True)

In [57]:
top100_full[top100_full['sepostulo'] == 1].shape

(35139, 2)

In [60]:
test = top100_full.sort_values('sepostulo', ascending=False)
test.shape

(159370, 2)

In [61]:
test.drop_duplicates('id', inplace=True)

In [63]:
test.shape

(100000, 2)

In [64]:
# top100_full.rename({'se_postulo' : 'sepostulo'}, inplace=True, axis=1)
test.to_csv('../data/adri_data/top100k_clf44.csv', encoding='utf-8', index=False)

In [42]:
%matplotlib notebook
import numpy as np
import matplotlib.pyplot as plt

In [43]:
from sklearn.ensemble import RandomForestClassifier


In [44]:
from sklearn.datasets import load_digits
from sklearn.ensemble import GradientBoostingClassifier

digits = load_digits()
X_digits, y_digits = digits.data, digits.target

# divide el dataset y aplica búsqueda grid

In [9]:
X, y = X_digits[y_digits < 2], y_digits[y_digits < 2]

rf = RandomForestClassifier(n_estimators=300, n_jobs=1)
rf.fit(X, y)
print(rf.feature_importances_)  # un valor por característica

[  0.00000000e+00   0.00000000e+00   5.81718181e-04   7.13264230e-03
   2.97260599e-04   3.15530272e-03   3.68508718e-03   0.00000000e+00
   0.00000000e+00   2.23993962e-04   1.58262940e-02   1.28247125e-03
   6.36487819e-04   5.14493236e-03   3.46076981e-04   0.00000000e+00
   1.80947916e-04   7.83958578e-03   9.16208015e-03   3.89173252e-02
   7.06862929e-02   2.84874738e-03   6.37622630e-03   0.00000000e+00
   1.58749718e-04   9.05356779e-03   3.13715978e-04   6.07056779e-02
   1.44744845e-01   3.55916252e-03   9.82889144e-02   0.00000000e+00
   0.00000000e+00   2.22067095e-02   6.18280531e-03   3.85758948e-02
   1.61565549e-01   4.89840433e-03   7.36949531e-02   0.00000000e+00
   0.00000000e+00   1.75193795e-02   1.85814854e-02   7.12423373e-03
   6.91643697e-02   4.01591187e-03   3.77947732e-02   0.00000000e+00
   0.00000000e+00   1.05251650e-03   2.59415626e-02   3.31264397e-03
   4.97826517e-04   2.88543969e-03   2.39239436e-04   8.62429108e-04
   0.00000000e+00   0.00000000e+00

In [59]:
from sklearn.ensemble import GradientBoostingRegressor
clf = GradientBoostingRegressor(n_estimators=100, max_depth=5, learning_rate=.2)
clf.fit(X_train, y_train)

print(clf.score(X_train, y_train))
print(clf.score(X_test, y_test))

ValueError: bad input shape (65, 11)