In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
%matplotlib inline

In [3]:
train_data = pd.read_csv('../data/final_data/full_datos_entrenamiento.csv')
train_data.head()

FileNotFoundError: File b'../data/final_data/full_datos_entrenamiento.csv' does not exist

In [ ]:
lb_make = LabelEncoder()
train_data["idpostulante2"] = lb_make.fit_transform(train_data["idpostulante"])
train_data[["idpostulante", "idpostulante2"]].head()

In [ ]:
train_data.drop(['idpostulante','Unnamed: 0'], axis=1, inplace=True)

In [ ]:
train_data = train_data[['idaviso', 'idpostulante2', 'valor_educacion', 'sexo', 'edad', 'idtitulo', 'idtipo_de_trabajo', 'idnivel_laboral', 'idnombre_area', 'iddenominacion_empresa', 'se_postulo']]
train_data.head()

In [ ]:
train_data.rename( {'idpostulante2':'idpostulante'}, axis=1, inplace=True)
train_data.head()

In [3]:
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier




In [2]:
df = pd.read_csv('../data/final_data/entrenamiento_postulaciones_vistas4.csv', encoding='utf-8')
df.head()

idaviso  idpostulante     timestamp  valor_educacion  sexo  idtitulo  \
0  1111556097        365446  7.038007e+06               17     1         0   
1  1112370711        365446  7.476885e+06               17     1      6996   
2  1112326655        365446  9.809277e+06               17     1     11827   
3  1112350182        365446  8.856385e+06               17     1      2141   
4  1112383837        365446  7.563903e+06               17     1      6942   

   idzona  idciudad  idmapacalle  idtipo_de_trabajo  idnivel_laboral  \
0       0         0            0                  0                0   
1       0         0            0                  0                0   
2       0         0            0                  0                0   
3       0         0            0                  0                0   
4       0         0            0                  0                0   

   idnombre_area  iddenominacion_empresa  se_postulo  
0              0                       0           1  
1             45                      14           1  
2              4                      33           1  
3             31                      38           1  
4             75                      46           1

In [4]:
# X will have the numeric data, Y will have the target class
dfix = df.ix[:, 0:13];
X = np.array(dfix)
y = np.array(df['se_postulo'])

/home/ariel/.local/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  


In [5]:
# Split into train and test, use only 10% as test (15 flowers)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10, random_state=7506)
X_test

array([[1.11241876e+09, 2.56340000e+04, 4.17343225e+06, ...,
        0.00000000e+00, 7.60000000e+01, 1.00000000e+01],
       [1.11234254e+09, 1.24354000e+05, 8.95024431e+06, ...,
        0.00000000e+00, 1.30000000e+01, 1.79200000e+03],
       [1.11227764e+09, 2.26590000e+05, 1.04896253e+07, ...,
        2.00000000e+00, 4.70000000e+01, 4.38000000e+02],
       ...,
       [1.11237865e+09, 1.52443000e+05, 7.56528031e+06, ...,
        0.00000000e+00, 4.00000000e+00, 6.14000000e+02],
       [1.11219014e+09, 1.04065000e+05, 1.13564083e+07, ...,
        0.00000000e+00, 6.00000000e+00, 2.10000000e+01],
       [1.11231222e+09, 2.06854000e+05, 1.00026573e+07, ...,
        0.00000000e+00, 0.00000000e+00, 4.60000000e+01]])

In [ ]:
clf = DecisionTreeClassifier(max_depth=45)
clf.fit(X_train, y_train)

In [ ]:
# predict the response
pred = clf.predict(X_test)
pred.shape

In [ ]:
print (accuracy_score(y_test, pred))
#max_depth 5 = 0.814749151461
#max_depth 7 = 0.817316995361
#max_depth 9 = 0.830302649952
#max_depth 11 = 0.836146456009
#max_depth 13 = 0.83922786869
#max_depth 15 = 0.842802976816
#max_depth 17 = 0.846111363886
#max_depth 19 = 0.848940699018
#max_depth 21 = 0.852105788893
#max_depth 23 = 0.85494662964
#max_depth 25 = 0.857750861614
#max_depth 27 = 0.860772654293
#max_depth 29 = 0.86390636522
#max_depth 31 = 0.8661049835
#max_depth 35 = 0.869442657588
#max_depth 41 = 0.871770975519
#max_depth 43 = 0.872110914121
#max_depth 44 = 0.872015731313
#max_depth 45 = 0.872120327805
#max_depth 46 = 0.871702987799
#max_depth 47 = 0.872014685348
#max_depth 49 = 0.871613034815
#max_depth 51 = 0.8717626078
#max_depth 61 = 0.8717626078


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=7506)

In [ ]:
clf = DecisionTreeClassifier(max_depth=45)
clf.fit(X_train, y_train)

In [ ]:
# predict the response
pred = clf.predict(X_test)
pred.shape

In [ ]:
print (accuracy_score(y_test, pred))

In [ ]:
pred.size

In [ ]:
df.size

In [ ]:
X_full_data = np.array(dfix)
X_full_data

In [ ]:
pred_full_data = clf.predict(X_full_data)

In [ ]:
pred_full_data

In [ ]:
df['sepostulo'] = pred_full_data

In [ ]:
df

## File a subir 

In [ ]:
top100 = pd.read_csv("../test_final_100k.csv", encoding='utf-8')

In [101]:
id_postulantes = pd.read_csv('../data/final_data/entrenamiento_id_postulantes.csv', encoding='utf-8')
id_postulantes.drop('Unnamed: 0', axis=1, inplace=True)
id_postulantes.shape
id_postulantes.head()

idpostulante  idpostulante2
0      pzeVW63         365446
1      PmVbBWY         209736
2      zvPMxvJ         409297
3       YYwJKq         250105
4      3NkMAVq          37024

In [102]:
top100_full = pd.merge(top100, id_postulantes, how='left', on='idpostulante')
top100_full.shape

(100000, 4)

In [103]:
top100_full.drop('idpostulante', inplace=True, axis=1)
top100_full.rename({'idpostulante2':'idpostulante'}, inplace=True, axis=1)
top100_full.head()

id  idaviso  idpostulante
0   0   739260       63651.0
1   1   739260       76877.0
2   2   739260      323397.0
3   3   758580           NaN
4   4   758580      127342.0

In [104]:
top100_full = pd.merge(top100_full, df, how='left', on=['idaviso','idpostulante'])
top100_full.shape

(100000, 16)

In [105]:
top100_full = top100_full[['id', 'se_postulo', 'sepostulo']]
top100_full.head()

id  se_postulo  sepostulo
0   0         NaN        NaN
1   1         NaN        NaN
2   2         NaN        NaN
3   3         NaN        NaN
4   4         NaN        NaN

In [106]:
top100_full.fillna(0, inplace=True)

In [107]:
top100_full['se_postulo'] = top100_full['se_postulo'].astype('int')
top100_full['sepostulo'] = top100_full['sepostulo'].astype('int')
top100_full.head()

id  se_postulo  sepostulo
0   0           0          0
1   1           0          0
2   2           0          0
3   3           0          0
4   4           0          0

In [108]:
top100_full.loc[(top100_full['sepostulo'] == 0) & (top100_full['se_postulo'] == 1), 'sepostulo'] = 1
top100_full[(top100_full['sepostulo'] == 0) & (top100_full['se_postulo'] == 1)]['sepostulo']

Series([], Name: sepostulo, dtype: int64)

In [109]:
top100_full.drop('se_postulo', axis=1, inplace=True)

In [110]:
top100_full[top100_full['sepostulo'] == 1].shape

(33892, 2)

In [111]:
# top100_full.rename({'se_postulo' : 'sepostulo'}, inplace=True, axis=1)
top100_full.to_csv('../data/entrega/top100k_clf44.csv', encoding='utf-8', index=False)

In [42]:
%matplotlib notebook
import numpy as np
import matplotlib.pyplot as plt

In [43]:
from sklearn.ensemble import RandomForestClassifier


In [44]:
from sklearn.datasets import load_digits
from sklearn.ensemble import GradientBoostingClassifier

digits = load_digits()
X_digits, y_digits = digits.data, digits.target

# divide el dataset y aplica búsqueda grid

In [9]:
X, y = X_digits[y_digits < 2], y_digits[y_digits < 2]

rf = RandomForestClassifier(n_estimators=300, n_jobs=1)
rf.fit(X, y)
print(rf.feature_importances_)  # un valor por característica

[  0.00000000e+00   0.00000000e+00   5.81718181e-04   7.13264230e-03
   2.97260599e-04   3.15530272e-03   3.68508718e-03   0.00000000e+00
   0.00000000e+00   2.23993962e-04   1.58262940e-02   1.28247125e-03
   6.36487819e-04   5.14493236e-03   3.46076981e-04   0.00000000e+00
   1.80947916e-04   7.83958578e-03   9.16208015e-03   3.89173252e-02
   7.06862929e-02   2.84874738e-03   6.37622630e-03   0.00000000e+00
   1.58749718e-04   9.05356779e-03   3.13715978e-04   6.07056779e-02
   1.44744845e-01   3.55916252e-03   9.82889144e-02   0.00000000e+00
   0.00000000e+00   2.22067095e-02   6.18280531e-03   3.85758948e-02
   1.61565549e-01   4.89840433e-03   7.36949531e-02   0.00000000e+00
   0.00000000e+00   1.75193795e-02   1.85814854e-02   7.12423373e-03
   6.91643697e-02   4.01591187e-03   3.77947732e-02   0.00000000e+00
   0.00000000e+00   1.05251650e-03   2.59415626e-02   3.31264397e-03
   4.97826517e-04   2.88543969e-03   2.39239436e-04   8.62429108e-04
   0.00000000e+00   0.00000000e+00

In [6]:
from sklearn.ensemble import GradientBoostingRegressor
clf = GradientBoostingRegressor(n_estimators=100, max_depth=5, learning_rate=.2)
clf.fit(X_train, y_train)



GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
             learning_rate=0.2, loss='ls', max_depth=5, max_features=None,
             max_leaf_nodes=None, min_impurity_decrease=0.0,
             min_impurity_split=None, min_samples_leaf=1,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             n_estimators=100, presort='auto', random_state=None,
             subsample=1.0, verbose=0, warm_start=False)

In [7]:
pred = clf.predict(X_test)

In [10]:
print(pred)

[0.53097979 0.99714418 1.00953215 ... 0.97786578 0.99507116 0.99044459]


In [15]:
def to_bool(pred):
    new_pred = []
    for predict in pred:
        if ( predict > 0.7):
            new_pred.append(1)
        else:
            new_pred.append(0)
    
    return new_pred

new_pred = to_bool(pred)

In [ ]:
print(new_pred)

In [17]:
print(accuracy_score( y_test, new_pred))

0.8380982265664633


## Ahora mergeo todo para subirlo

In [18]:
X_full_data = np.array(dfix)
X_full_data

array([[1.11155610e+09, 3.65446000e+05, 7.03800731e+06, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.11237071e+09, 3.65446000e+05, 7.47688531e+06, ...,
        0.00000000e+00, 4.50000000e+01, 1.40000000e+01],
       [1.11232666e+09, 3.65446000e+05, 9.80927731e+06, ...,
        0.00000000e+00, 4.00000000e+00, 3.30000000e+01],
       ...,
       [1.11160188e+09, 3.23892000e+05, 8.13147410e+06, ...,
        0.00000000e+00, 6.00000000e+00, 7.10000000e+01],
       [1.11131998e+09, 3.99727000e+05, 8.12986248e+06, ...,
        0.00000000e+00, 3.00000000e+00, 3.29000000e+02],
       [1.11208492e+09, 1.20330000e+05, 8.12629305e+06, ...,
        0.00000000e+00, 1.40000000e+01, 1.85000000e+03]])

In [19]:
pred_full_data = clf.predict(X_full_data)

In [22]:
pred_data = to_bool(pred_full_data)

In [25]:
print(pred_data)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [26]:
df['sepostulo'] = pred_data

In [27]:
df.head()

idaviso  idpostulante     timestamp  valor_educacion  sexo  idtitulo  \
0  1111556097        365446  7.038007e+06               17     1         0   
1  1112370711        365446  7.476885e+06               17     1      6996   
2  1112326655        365446  9.809277e+06               17     1     11827   
3  1112350182        365446  8.856385e+06               17     1      2141   
4  1112383837        365446  7.563903e+06               17     1      6942   

   idzona  idciudad  idmapacalle  idtipo_de_trabajo  idnivel_laboral  \
0       0         0            0                  0                0   
1       0         0            0                  0                0   
2       0         0            0                  0                0   
3       0         0            0                  0                0   
4       0         0            0                  0                0   

   idnombre_area  iddenominacion_empresa  se_postulo  sepostulo  
0              0                       0           1          1  
1             45                      14           1          1  
2              4                      33           1          1  
3             31                      38           1          1  
4             75                      46           1          1

## Subida 

In [29]:
top100 = pd.read_csv("../test_final_100k.csv", encoding='utf-8')

In [31]:
id_postulantes = pd.read_csv('../data/final_data/entrenamiento_id_postulantes.csv', encoding='utf-8')
id_postulantes.drop('Unnamed: 0', axis=1, inplace=True)
id_postulantes.shape
id_postulantes.head()

idpostulante  idpostulante2
0      pzeVW63         365446
1      PmVbBWY         209736
2      zvPMxvJ         409297
3       YYwJKq         250105
4      3NkMAVq          37024

In [32]:
top100_full = pd.merge(top100, id_postulantes, how='left', on='idpostulante')
top100_full.shape

(100000, 4)

In [33]:
top100_full.drop('idpostulante', inplace=True, axis=1)
top100_full.rename({'idpostulante2':'idpostulante'}, inplace=True, axis=1)
top100_full.head()

id  idaviso  idpostulante
0   0   739260       63651.0
1   1   739260       76877.0
2   2   739260      323397.0
3   3   758580           NaN
4   4   758580      127342.0

In [34]:
top100_full = pd.merge(top100_full, df, how='left', on=['idaviso','idpostulante'])
top100_full.shape

(100000, 16)