In [1]:
import pandas as pd
import numpy as np
import datetime as dt
from sklearn import linear_model
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

from sklearn.neighbors.nearest_centroid import NearestCentroid

from sklearn.cross_validation import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
%matplotlib inline

/home/sebastian/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
# full_data = pd.read_csv('../data/adri_data/entrenamiento_postulaciones_vistas3.csv', encoding='utf-8')
# full_data.shape

In [3]:
# full_data.head()

In [4]:
# df = full_data[['idaviso', 'idpostulante', 'timestamp', 'valor_educacion', 'sexo', 'idtitulo', 
# 'idzona', 'idciudad', 'idmapacalle', 'idtipo_de_trabajo',
# 'idnivel_laboral', 'idnombre_area', 'iddenominacion_empresa', 'se_postulo']]
# 
# df['timestamp'] = df['timestamp'].apply(pd.to_datetime)
# 
# now = pd.Timestamp(dt.datetime.now())
# pd.to_datetime(now)
# 
# df['timestamp'] = (now - df['timestamp']).apply(lambda x: x.total_seconds())
# df.to_csv('../data/adri_data/entrenamiento_postulaciones_vistas4.csv', encoding='utf-8', index=False)

In [5]:
df = pd.read_csv('../data/final_data/entrenamiento_postulaciones_vistas4.csv', encoding='utf-8')
df.head()

idaviso  idpostulante     timestamp  valor_educacion  sexo  idtitulo  \
0  1111556097        365446  7.038007e+06               17     1         0   
1  1112370711        365446  7.476885e+06               17     1      6996   
2  1112326655        365446  9.809277e+06               17     1     11827   
3  1112350182        365446  8.856385e+06               17     1      2141   
4  1112383837        365446  7.563903e+06               17     1      6942   

   idzona  idciudad  idmapacalle  idtipo_de_trabajo  idnivel_laboral  \
0       0         0            0                  0                0   
1       0         0            0                  0                0   
2       0         0            0                  0                0   
3       0         0            0                  0                0   
4       0         0            0                  0                0   

   idnombre_area  iddenominacion_empresa  se_postulo  
0              0                       0           1  
1             45                      14           1  
2              4                      33           1  
3             31                      38           1  
4             75                      46           1

In [6]:
# X will have the numeric data, Y will have the target class
dfix = df.ix[:, 0:13];
X = np.array(dfix)
y = np.array(df['se_postulo']) 

/home/sebastian/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  


In [7]:
# Split into train and test, use only 10% as test (15 flowers)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10, random_state=7506)
X_test

array([[1.11241876e+09, 2.56340000e+04, 4.17343225e+06, ...,
        0.00000000e+00, 7.60000000e+01, 1.00000000e+01],
       [1.11234254e+09, 1.24354000e+05, 8.95024431e+06, ...,
        0.00000000e+00, 1.30000000e+01, 1.79200000e+03],
       [1.11227764e+09, 2.26590000e+05, 1.04896253e+07, ...,
        2.00000000e+00, 4.70000000e+01, 4.38000000e+02],
       ...,
       [1.11237865e+09, 1.52443000e+05, 7.56528031e+06, ...,
        0.00000000e+00, 4.00000000e+00, 6.14000000e+02],
       [1.11219014e+09, 1.04065000e+05, 1.13564083e+07, ...,
        0.00000000e+00, 6.00000000e+00, 2.10000000e+01],
       [1.11231222e+09, 2.06854000e+05, 1.00026573e+07, ...,
        0.00000000e+00, 0.00000000e+00, 4.60000000e+01]])

In [8]:
y_test

array([0, 1, 1, ..., 1, 1, 1])

In [9]:
clf = NearestCentroid()

In [10]:
clf.fit(X_train, y_train)

NearestCentroid(metric='euclidean', shrink_threshold=None)

In [11]:
clf.score(X_test, y_test)

0.7924816040918148

In [12]:
# predict the response
pred = clf.predict(X_test)
pred.shape

(956055,)

In [13]:
# evaluate accuracy
print (accuracy_score(y_test, pred)) # 3 = 0.8726778271124569

0.7924816040918148


In [14]:
pred_df = pd.DataFrame(pred)
pred_df.head()

0
0  0
1  1
2  1
3  0
4  1

# Predigo con todos los datos

In [15]:
X_full_data = np.array(dfix)
X_full_data

array([[1.11155610e+09, 3.65446000e+05, 7.03800731e+06, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.11237071e+09, 3.65446000e+05, 7.47688531e+06, ...,
        0.00000000e+00, 4.50000000e+01, 1.40000000e+01],
       [1.11232666e+09, 3.65446000e+05, 9.80927731e+06, ...,
        0.00000000e+00, 4.00000000e+00, 3.30000000e+01],
       ...,
       [1.11160188e+09, 3.23892000e+05, 8.13147410e+06, ...,
        0.00000000e+00, 6.00000000e+00, 7.10000000e+01],
       [1.11131998e+09, 3.99727000e+05, 8.12986248e+06, ...,
        0.00000000e+00, 3.00000000e+00, 3.29000000e+02],
       [1.11208492e+09, 1.20330000e+05, 8.12629305e+06, ...,
        0.00000000e+00, 1.40000000e+01, 1.85000000e+03]])

In [16]:
pred_full_data = clf.predict(X_full_data)

In [17]:
pred_full_data

array([1, 1, 1, ..., 1, 1, 1])

In [18]:
df['sepostulo'] = pred_full_data

In [19]:
df

idaviso  idpostulante     timestamp  valor_educacion  sexo  \
0        1111556097        365446  7.038007e+06               17     1   
1        1112370711        365446  7.476885e+06               17     1   
2        1112326655        365446  9.809277e+06               17     1   
3        1112350182        365446  8.856385e+06               17     1   
4        1112383837        365446  7.563903e+06               17     1   
5        1112394991        365446  6.880681e+06               17     1   
6        1112387712        365446  7.477011e+06               17     1   
7        1112286220        365446  7.477295e+06               17     1   
8        1112399795        365446  6.880694e+06               17     1   
9        1112296014        365446  1.041792e+07               17     1   
10       1112289548        365446  1.110333e+07               17     1   
11       1112296354        365446  1.058453e+07               17     1   
12       1111967504        365446  1.058455e+07               17     1   
13       1112407372        365446  5.833123e+06               17     1   
14       1111984070        365446  1.058469e+07               17     1   
15       1112365178        365446  8.166029e+06               17     1   
16       1112252821        365446  1.196625e+07               17     1   
17       1112424614        365446  5.833008e+06               17     1   
18       1112336070        365446  6.347383e+06               17     1   
19       1112432317        365446  5.238732e+06               17     1   
20       1112458730        365446  4.534623e+06               17     1   
21       1112349399        365446  8.856358e+06               17     1   
22       1112463121        365446  4.358479e+06               17     1   
23       1112382267        365446  7.563827e+06               17     1   
24       1111556097        209736  7.114418e+06                6     2   
25       1112191071        209736  7.113933e+06                6     2   
26       1111891857        209736  7.114277e+06                6     2   
27       1112422110        209736  6.165200e+06                6     2   
28       1112396891        209736  7.022333e+06                6     2   
29       1112353872        209736  8.757222e+06                6     2   
...             ...           ...           ...              ...   ...   
9560513  1112054114        157394  8.117187e+06               10    -1   
9560514  1112194374        385974  8.205502e+06                4     1   
9560515  1112296586        118649  8.182859e+06               10     1   
9560516  1111947938        348860  8.177229e+06                6     2   
9560517  1111682210        256357  8.178258e+06               12     1   
9560518  1111682210         69137  8.132904e+06               10     1   
9560519  1111923911        153813  8.161264e+06               12     1   
9560520  1111549543        379758  8.152359e+06               11     1   
9560521  1111840748        342668  8.176790e+06               10     2   
9560522  1111177561         31690  8.170182e+06               10     1   
9560523  1111858589         23662  8.164315e+06               12     2   
9560524  1111322472        104312  8.161582e+06                6     2   
9560525  1111469472        390629  8.157012e+06                5     1   
9560526  1111471769        374031  8.154819e+06               10     2   
9560527  1111460314         22534  8.155403e+06               12     2   
9560528  1112087976         51478  8.151352e+06                8     2   
9560529  1112097280        113023  8.148473e+06               10     1   
9560530  1000872556        325512  8.123154e+06                6     2   
9560531  1112055574        169268  8.144875e+06                6     1   
9560532  1112100433        132814  8.144750e+06               11     1   
9560533  1112049386        352522  8.135747e+06                6     2   
9560534  1112226525         52119  8.141612e+06                8     1   
9560535  1111872

# Finalmente, preparo el archivo para subir-

In [20]:
top100 = pd.read_csv("../test_final_100k.csv", encoding='utf-8')
top100.head()

id  idaviso idpostulante
0   0   739260       6M9ZQR
1   1   739260       6v1xdL
2   2   739260       ezRKm9
3   3   758580       1Q35ej
4   4   758580       EAN4J6

In [21]:
top100.shape

(100000, 3)

In [22]:
id_postulantes = pd.read_csv('../data/final_data/entrenamiento_id_postulantes.csv', encoding='utf-8')
#id_postulantes.drop('Unnamed: 0', axis=1, inplace=True)
id_postulantes.shape
id_postulantes.head()

idpostulante  idpostulante2
0      pzeVW63         365446
1      PmVbBWY         209736
2      zvPMxvJ         409297
3       YYwJKq         250105
4      3NkMAVq          37024

In [23]:
top100_full = pd.merge(top100, id_postulantes, how='left', on='idpostulante')
top100_full.shape

(100000, 4)

In [24]:
top100_full.drop('idpostulante', inplace=True, axis=1)
top100_full.rename({'idpostulante2':'idpostulante'}, inplace=True, axis=1)
top100_full.head()

id  idaviso  idpostulante
0   0   739260       63651.0
1   1   739260       76877.0
2   2   739260      323397.0
3   3   758580           NaN
4   4   758580      127342.0

In [25]:
top100_full = pd.merge(top100_full, df, how='left', on=['idaviso','idpostulante'])
top100_full.shape

(100000, 16)

In [26]:
top100_full = top100_full[['id', 'se_postulo', 'sepostulo']]
top100_full.head()

id  se_postulo  sepostulo
0   0         NaN        NaN
1   1         NaN        NaN
2   2         NaN        NaN
3   3         NaN        NaN
4   4         NaN        NaN

In [27]:
top100_full.fillna(0, inplace=True)

In [28]:
top100_full['se_postulo'] = top100_full['se_postulo'].astype('int')
top100_full['sepostulo'] = top100_full['sepostulo'].astype('int')
top100_full.head()

id  se_postulo  sepostulo
0   0           0          0
1   1           0          0
2   2           0          0
3   3           0          0
4   4           0          0

In [29]:
top100_full.loc[(top100_full['sepostulo'] == 0) & (top100_full['se_postulo'] == 1), 'sepostulo'] = 1
top100_full[(top100_full['sepostulo'] == 0) & (top100_full['se_postulo'] == 1)]['sepostulo']

Series([], Name: sepostulo, dtype: int64)

In [30]:
top100_full.drop('se_postulo', axis=1, inplace=True)

In [31]:
top100_full[top100_full['sepostulo'] == 1].shape

(33547, 2)

In [32]:
# top100_full.rename({'se_postulo' : 'sepostulo'}, inplace=True, axis=1)
top100_full.to_csv('../data/final_data/top100k.csv', encoding='utf-8', index=False)