In [3]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import BernoulliNB

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [5]:
#Load all binary classifiers
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

seed = 123
models = []
models.append(('logreg', LogisticRegression()))
models.append(('cart', DecisionTreeClassifier()))
models.append(('rfc', RandomForestClassifier()))
models.append(('gbc', GradientBoostingClassifier()))
models.append(('knn', KNeighborsClassifier()))
models.append(('lda', LinearDiscriminantAnalysis()))
models.append(('nb', GaussianNB()))
models.append(('svc', SVC()))

In [6]:
df = pd.read_csv('../data/final_data/entrenamiento_postulaciones_vistas4.csv', encoding='utf-8')
df.head()

idaviso  idpostulante     timestamp  valor_educacion  sexo  idtitulo  \
0  1111556097        365446  7.038007e+06               17     1         0   
1  1112370711        365446  7.476885e+06               17     1      6996   
2  1112326655        365446  9.809277e+06               17     1     11827   
3  1112350182        365446  8.856385e+06               17     1      2141   
4  1112383837        365446  7.563903e+06               17     1      6942   

   idzona  idciudad  idmapacalle  idtipo_de_trabajo  idnivel_laboral  \
0       0         0            0                  0                0   
1       0         0            0                  0                0   
2       0         0            0                  0                0   
3       0         0            0                  0                0   
4       0         0            0                  0                0   

   idnombre_area  iddenominacion_empresa  se_postulo  
0              0                       0           1  
1             45                      14           1  
2              4                      33           1  
3             31                      38           1  
4             75                      46           1

In [7]:
# X will have the numeric data, Y will have the target class
dfix = df.ix[:, 0:13];
X = np.array(dfix)
y = np.array(df['se_postulo']) 

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  


In [9]:
!pip install imblearn

    100% |████████████████████████████████| 153kB 4.3MB/s ta 0:00:01
You are using pip version 10.0.0, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [10]:
#Correct the unbalanced dataset
from imblearn.under_sampling import RandomUnderSampler
rus = RandomUnderSampler()
data_x_balanced, data_y_balanced = rus.fit_sample(X, y)

In [11]:
from collections import Counter
Counter(data_y_balanced) #Counter({0: 3561762, 1: 3561762})

Counter({0: 3561762, 1: 3561762})

In [12]:
#Define training and test sets
from sklearn.cross_validation import train_test_split
train_x, test_x, train_y, test_y = train_test_split(data_x_balanced, data_y_balanced, test_size = 0.25)
train_x.shape #354 cells and 9 features
test_x.shape #118 cells and 9 features

/usr/local/lib/python3.5/dist-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


(1780881, 13)

In [ ]:
#Cross validation training for all models
seed=123
results = []
names = []
scoring = 'accuracy'
print("10-fold CV Train Accuracy:")
for name, model in models:
    kfold = model_selection.KFold(n_splits=10, random_state=seed)
    cv_scores = model_selection.cross_val_score(model, train_x, train_y, cv=kfold, scoring=scoring)
    results.append(cv_scores)
    names.append(name)
    msg = "  %s: %0.3f (+/- %0.3f)" % (name, cv_scores.mean(), cv_scores.std())
    print(msg)

10-fold CV Train Accuracy:
  logreg: 0.817 (+/- 0.000)
  cart: 0.861 (+/- 0.001)
  rfc: 0.862 (+/- 0.001)
  gbc: 0.848 (+/- 0.001)
  knn: 0.868 (+/- 0.000)
  lda: 0.816 (+/- 0.001)
  nb: 0.805 (+/- 0.001)


In [ ]:
results = []
names = []
scores = 'accuracy'
print("10-fold CV Test Accuracy:")
for name, model in models:
    kfold = model_selection.KFold(n_splits=10, random_state=seed)
    cv_preds = model_selection.cross_val_predict(model, test_x, test_y, cv=kfold)
    names.append(name)
    print ("  %s: %0.3f" % (name, metrics.accuracy_score(test_y, cv_preds)))

In [6]:
# Split into train and test, use only 10% as test (15 flowers)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10, random_state=7506)
X_test

array([[  1.11241876e+09,   2.56340000e+04,   4.17343225e+06, ...,
          0.00000000e+00,   7.60000000e+01,   1.00000000e+01],
       [  1.11234254e+09,   1.24354000e+05,   8.95024431e+06, ...,
          0.00000000e+00,   1.30000000e+01,   1.79200000e+03],
       [  1.11227764e+09,   2.26590000e+05,   1.04896253e+07, ...,
          2.00000000e+00,   4.70000000e+01,   4.38000000e+02],
       ..., 
       [  1.11237865e+09,   1.52443000e+05,   7.56528031e+06, ...,
          0.00000000e+00,   4.00000000e+00,   6.14000000e+02],
       [  1.11219014e+09,   1.04065000e+05,   1.13564083e+07, ...,
          0.00000000e+00,   6.00000000e+00,   2.10000000e+01],
       [  1.11231222e+09,   2.06854000e+05,   1.00026573e+07, ...,
          0.00000000e+00,   0.00000000e+00,   4.60000000e+01]])

In [7]:
gnb = GaussianNB()

In [11]:
pred = gnb.fit(X_train, y_train).predict(X_test)

In [12]:
print (accuracy_score(y_test, pred))

0.797158113288


## Multinomial 

In [22]:
clf = BernoulliNB()

In [23]:
clf.fit(X_train, y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [24]:
pred = clf.predict(X_test)

In [25]:
print (accuracy_score(y_test, pred))

0.627231696921


## Uso gaussiano

## Total datos

In [27]:
# Split into train and test, use only 10% as test (15 flowers)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=7506)
X_test

array([[  1.11241876e+09,   2.56340000e+04,   4.17343225e+06, ...,
          0.00000000e+00,   7.60000000e+01,   1.00000000e+01],
       [  1.11234254e+09,   1.24354000e+05,   8.95024431e+06, ...,
          0.00000000e+00,   1.30000000e+01,   1.79200000e+03],
       [  1.11227764e+09,   2.26590000e+05,   1.04896253e+07, ...,
          2.00000000e+00,   4.70000000e+01,   4.38000000e+02],
       ..., 
       [  1.11239744e+09,   1.78446000e+05,   4.74903463e+06, ...,
          1.00000000e+00,   5.30000000e+01,   3.65500000e+03],
       [  1.11166223e+09,   2.86619000e+05,   1.12488263e+07, ...,
          1.00000000e+00,   1.90000000e+01,   1.13000000e+03],
       [  1.11235984e+09,   1.52316000e+05,   8.57449731e+06, ...,
          0.00000000e+00,   1.12000000e+02,   5.77000000e+02]])

In [28]:
pred = gnb.fit(X_train, y_train).predict(X_test)

In [29]:
print (accuracy_score(y_test, pred))

0.797327432414


In [30]:
pred.shape

(2390136,)

In [31]:
X_full_data = np.array(dfix)
X_full_data

array([[  1.11155610e+09,   3.65446000e+05,   7.03800731e+06, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  1.11237071e+09,   3.65446000e+05,   7.47688531e+06, ...,
          0.00000000e+00,   4.50000000e+01,   1.40000000e+01],
       [  1.11232666e+09,   3.65446000e+05,   9.80927731e+06, ...,
          0.00000000e+00,   4.00000000e+00,   3.30000000e+01],
       ..., 
       [  1.11160188e+09,   3.23892000e+05,   8.13147410e+06, ...,
          0.00000000e+00,   6.00000000e+00,   7.10000000e+01],
       [  1.11131998e+09,   3.99727000e+05,   8.12986248e+06, ...,
          0.00000000e+00,   3.00000000e+00,   3.29000000e+02],
       [  1.11208492e+09,   1.20330000e+05,   8.12629305e+06, ...,
          0.00000000e+00,   1.40000000e+01,   1.85000000e+03]])

In [32]:
pred_full_data = clf.predict(X_full_data)

In [33]:
df['sepostulo'] = pred_full_data

In [34]:
df.head()

idaviso  idpostulante     timestamp  valor_educacion  sexo  idtitulo  \
0  1111556097        365446  7.038007e+06               17     1         0   
1  1112370711        365446  7.476885e+06               17     1      6996   
2  1112326655        365446  9.809277e+06               17     1     11827   
3  1112350182        365446  8.856385e+06               17     1      2141   
4  1112383837        365446  7.563903e+06               17     1      6942   

   idzona  idciudad  idmapacalle  idtipo_de_trabajo  idnivel_laboral  \
0       0         0            0                  0                0   
1       0         0            0                  0                0   
2       0         0            0                  0                0   
3       0         0            0                  0                0   
4       0         0            0                  0                0   

   idnombre_area  iddenominacion_empresa  se_postulo  sepostulo  
0              0                       0           1          1  
1             45                      14           1          1  
2              4                      33           1          1  
3             31                      38           1          1  
4             75                      46           1          1

## Subida 

In [35]:
top100 = pd.read_csv("../test_final_100k.csv", encoding='utf-8')

In [36]:
id_postulantes = pd.read_csv('../data/final_data/entrenamiento_id_postulantes.csv', encoding='utf-8')
id_postulantes.drop('Unnamed: 0', axis=1, inplace=True)
id_postulantes.shape
id_postulantes.head()

idpostulante  idpostulante2
0      pzeVW63         365446
1      PmVbBWY         209736
2      zvPMxvJ         409297
3       YYwJKq         250105
4      3NkMAVq          37024

In [37]:
top100_full = pd.merge(top100, id_postulantes, how='left', on='idpostulante')
top100_full.shape

(100000, 4)

In [38]:
top100_full.drop('idpostulante', inplace=True, axis=1)
top100_full.rename({'idpostulante2':'idpostulante'}, inplace=True, axis=1)
top100_full.head()

id  idaviso  idpostulante
0   0   739260       63651.0
1   1   739260       76877.0
2   2   739260      323397.0
3   3   758580           NaN
4   4   758580      127342.0

In [39]:
top100_full = pd.merge(top100_full, df, how='left', on=['idaviso','idpostulante'])
top100_full.shape

(100000, 16)

In [40]:
top100_full = top100_full[['id', 'se_postulo', 'sepostulo']]
top100_full.head()

id  se_postulo  sepostulo
0   0         NaN        NaN
1   1         NaN        NaN
2   2         NaN        NaN
3   3         NaN        NaN
4   4         NaN        NaN

In [41]:
top100_full.fillna(0, inplace=True)

In [42]:
top100_full['se_postulo'] = top100_full['se_postulo'].astype('int')
top100_full['sepostulo'] = top100_full['sepostulo'].astype('int')
top100_full.head()

id  se_postulo  sepostulo
0   0           0          0
1   1           0          0
2   2           0          0
3   3           0          0
4   4           0          0

In [43]:
top100_full.loc[(top100_full['sepostulo'] == 0) & (top100_full['se_postulo'] == 1), 'sepostulo'] = 1
top100_full[(top100_full['sepostulo'] == 0) & (top100_full['se_postulo'] == 1)]['sepostulo']

Series([], Name: sepostulo, dtype: int64)

In [44]:
top100_full.drop('se_postulo', axis=1, inplace=True)

In [45]:
top100_full[top100_full['sepostulo'] == 1].shape

(38595, 2)

In [46]:
# top100_full.rename({'se_postulo' : 'sepostulo'}, inplace=True, axis=1)
top100_full.to_csv('../data/entrega/top100k_gnb.csv', encoding='utf-8', index=False)

# Con otros files