In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
from sklearn.linear_model import SGDClassifier

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
from sklearn.metrics import accuracy_score

In [5]:
df = pd.read_csv('../data/final_data/entrenamiento_postulaciones_vistas4.csv', encoding='utf-8')
df.head()

idaviso  idpostulante     timestamp  valor_educacion  sexo  idtitulo  \
0  1111556097        365446  7.038007e+06               17     1         0   
1  1112370711        365446  7.476885e+06               17     1      6996   
2  1112326655        365446  9.809277e+06               17     1     11827   
3  1112350182        365446  8.856385e+06               17     1      2141   
4  1112383837        365446  7.563903e+06               17     1      6942   

   idzona  idciudad  idmapacalle  idtipo_de_trabajo  idnivel_laboral  \
0       0         0            0                  0                0   
1       0         0            0                  0                0   
2       0         0            0                  0                0   
3       0         0            0                  0                0   
4       0         0            0                  0                0   

   idnombre_area  iddenominacion_empresa  se_postulo  
0              0                       0           1  
1             45                      14           1  
2              4                      33           1  
3             31                      38           1  
4             75                      46           1

In [6]:
# X will have the numeric data, Y will have the target class
dfix = df.ix[:, 0:13];
X = np.array(dfix)
y = np.array(df['se_postulo']) 

/home/sebastian/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  


In [7]:
# Split into train and test, use only 10% as test (15 flowers)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10, random_state=7506)
X_test

array([[1.11241876e+09, 2.56340000e+04, 4.17343225e+06, ...,
        0.00000000e+00, 7.60000000e+01, 1.00000000e+01],
       [1.11234254e+09, 1.24354000e+05, 8.95024431e+06, ...,
        0.00000000e+00, 1.30000000e+01, 1.79200000e+03],
       [1.11227764e+09, 2.26590000e+05, 1.04896253e+07, ...,
        2.00000000e+00, 4.70000000e+01, 4.38000000e+02],
       ...,
       [1.11237865e+09, 1.52443000e+05, 7.56528031e+06, ...,
        0.00000000e+00, 4.00000000e+00, 6.14000000e+02],
       [1.11219014e+09, 1.04065000e+05, 1.13564083e+07, ...,
        0.00000000e+00, 6.00000000e+00, 2.10000000e+01],
       [1.11231222e+09, 2.06854000e+05, 1.00026573e+07, ...,
        0.00000000e+00, 0.00000000e+00, 4.60000000e+01]])

In [8]:
clf = SGDClassifier(loss="log", penalty="l2")
clf.fit(X_train, y_train)

/home/sebastian/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


SGDClassifier(alpha=0.0001, average=False, class_weight=None, epsilon=0.1,
       eta0=0.0, fit_intercept=True, l1_ratio=0.15,
       learning_rate='optimal', loss='log', max_iter=None, n_iter=None,
       n_jobs=1, penalty='l2', power_t=0.5, random_state=None,
       shuffle=True, tol=None, verbose=0, warm_start=False)

In [9]:
pred = clf.predict(X_test)

In [10]:
print (accuracy_score(y_test, pred))
# hinge y l2 = 0.703247198121
# modified_huber y l2 = 0.657787470386
# log y l2 = 0.80954338401
# log y l1 = 0.801240514406
# log y elasticnet = 0.804613751301
# hinge y elasticnet = 0.703875823044
# modified_huber y elasticnet = 0.765358687523
# modified_huber y l1 = 0.802019758278


0.799989540350712


In [11]:
clf.coef_

array([[-4.33367647e+05,  1.90016767e+05,  8.86538928e+07,
        -1.81689335e+01,  6.18375718e+01,  6.13181515e+04,
         4.76091649e+01,  2.67616915e+01,  1.79586713e+03,
         8.24806218e+00,  1.85588372e+02, -1.46118096e+03,
        -2.76235870e+04]])

In [12]:
clf.intercept_

array([-12.44821733])

## Ahora todos los datos

In [13]:
# Split into train and test, use only 10% as test (15 flowers)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=7506)
X_test

array([[1.11241876e+09, 2.56340000e+04, 4.17343225e+06, ...,
        0.00000000e+00, 7.60000000e+01, 1.00000000e+01],
       [1.11234254e+09, 1.24354000e+05, 8.95024431e+06, ...,
        0.00000000e+00, 1.30000000e+01, 1.79200000e+03],
       [1.11227764e+09, 2.26590000e+05, 1.04896253e+07, ...,
        2.00000000e+00, 4.70000000e+01, 4.38000000e+02],
       ...,
       [1.11239744e+09, 1.78446000e+05, 4.74903463e+06, ...,
        1.00000000e+00, 5.30000000e+01, 3.65500000e+03],
       [1.11166223e+09, 2.86619000e+05, 1.12488263e+07, ...,
        1.00000000e+00, 1.90000000e+01, 1.13000000e+03],
       [1.11235984e+09, 1.52316000e+05, 8.57449731e+06, ...,
        0.00000000e+00, 1.12000000e+02, 5.77000000e+02]])

In [14]:
clf = SGDClassifier(loss="log", penalty="l2")
clf.fit(X_train, y_train)

/home/sebastian/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


SGDClassifier(alpha=0.0001, average=False, class_weight=None, epsilon=0.1,
       eta0=0.0, fit_intercept=True, l1_ratio=0.15,
       learning_rate='optimal', loss='log', max_iter=None, n_iter=None,
       n_jobs=1, penalty='l2', power_t=0.5, random_state=None,
       shuffle=True, tol=None, verbose=0, warm_start=False)

In [15]:
pred = clf.predict(X_test)

In [16]:
print (accuracy_score(y_test, pred))

0.7987913658469643


In [17]:
pred.shape

(2390136,)

In [18]:
X_full_data = np.array(dfix)
X_full_data

array([[1.11155610e+09, 3.65446000e+05, 7.03800731e+06, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.11237071e+09, 3.65446000e+05, 7.47688531e+06, ...,
        0.00000000e+00, 4.50000000e+01, 1.40000000e+01],
       [1.11232666e+09, 3.65446000e+05, 9.80927731e+06, ...,
        0.00000000e+00, 4.00000000e+00, 3.30000000e+01],
       ...,
       [1.11160188e+09, 3.23892000e+05, 8.13147410e+06, ...,
        0.00000000e+00, 6.00000000e+00, 7.10000000e+01],
       [1.11131998e+09, 3.99727000e+05, 8.12986248e+06, ...,
        0.00000000e+00, 3.00000000e+00, 3.29000000e+02],
       [1.11208492e+09, 1.20330000e+05, 8.12629305e+06, ...,
        0.00000000e+00, 1.40000000e+01, 1.85000000e+03]])

In [19]:
pred_full_data = clf.predict(X_full_data)

In [20]:
df['sepostulo'] = pred_full_data

In [21]:
df.head()

idaviso  idpostulante     timestamp  valor_educacion  sexo  idtitulo  \
0  1111556097        365446  7.038007e+06               17     1         0   
1  1112370711        365446  7.476885e+06               17     1      6996   
2  1112326655        365446  9.809277e+06               17     1     11827   
3  1112350182        365446  8.856385e+06               17     1      2141   
4  1112383837        365446  7.563903e+06               17     1      6942   

   idzona  idciudad  idmapacalle  idtipo_de_trabajo  idnivel_laboral  \
0       0         0            0                  0                0   
1       0         0            0                  0                0   
2       0         0            0                  0                0   
3       0         0            0                  0                0   
4       0         0            0                  0                0   

   idnombre_area  iddenominacion_empresa  se_postulo  sepostulo  
0              0                       0           1          1  
1             45                      14           1          1  
2              4                      33           1          1  
3             31                      38           1          1  
4             75                      46           1          1

## File a subir 

In [22]:
top100 = pd.read_csv("../test_final_100k.csv", encoding='utf-8')

In [23]:
id_postulantes = pd.read_csv('../data/final_data/entrenamiento_id_postulantes.csv', encoding='utf-8')
id_postulantes.drop('Unnamed: 0', axis=1, inplace=True)
id_postulantes.shape
id_postulantes.head()

ValueError: labels ['Unnamed: 0'] not contained in axis

In [ ]:
top100_full = pd.merge(top100, id_postulantes, how='left', on='idpostulante')
top100_full.shape

In [ ]:
top100_full.drop('idpostulante', inplace=True, axis=1)
top100_full.rename({'idpostulante2':'idpostulante'}, inplace=True, axis=1)
top100_full.head()

In [ ]:
top100_full = pd.merge(top100_full, df, how='left', on=['idaviso','idpostulante'])
top100_full.shape

In [ ]:
top100_full = top100_full[['id', 'se_postulo', 'sepostulo']]
top100_full.head()

In [ ]:
top100_full.fillna(0, inplace=True)

In [ ]:
top100_full['se_postulo'] = top100_full['se_postulo'].astype('int')
top100_full['sepostulo'] = top100_full['sepostulo'].astype('int')
top100_full.head()

In [ ]:
top100_full.loc[(top100_full['sepostulo'] == 0) & (top100_full['se_postulo'] == 1), 'sepostulo'] = 1
top100_full[(top100_full['sepostulo'] == 0) & (top100_full['se_postulo'] == 1)]['sepostulo']

In [ ]:
top100_full.drop('se_postulo', axis=1, inplace=True)

In [ ]:
top100_full[top100_full['sepostulo'] == 1].shape

In [ ]:
# top100_full.rename({'se_postulo' : 'sepostulo'}, inplace=True, axis=1)
top100_full.to_csv('../data/entrega/top100k_sgdlogl2.csv', encoding='utf-8', index=False)